### PR TITLE
Reactions

### PR DESCRIPTION
**Pull request by quackers2**
Added reaction functionality. Currently, you have to hit refresh to see the changes and it does not limit people to one reaction.

### CODE REVIEW

**Comment by Mones26** [comment]
Reviewed Code in person

**Comment by jjpark2** [comment]
Also reviewed code in person

**Comment by jjpark2** [comment]
Also reviewed code in person

**Comment by kren333** [comment]
Approved PR just didnt click button -- went to OH to verify that this was an OK solution

**Pull request merged**
